# This is a basic workflow to help you get started with Actions

name: Deploy React App to Surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2.0.0
        with:
            node-version: 12
            
      - uses: borales/actions-yarn@v2.0.0
        with:
           cmd: install # will run 'yarn install' commnad
         
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install --global surge
      - name: Deploy Surge
        run: surge ./build nasir-project004.surge.sh --token $ {{secrets.SURGE_TOKEN}}

     
